package View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRAKTIKUM
 */
public class BatalPesanan extends javax.swing.JFrame {

    /**
     * Creates new form BatalPesanan
     */
    public BatalPesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        btnBatalPesan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnDaftarTransaksi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboPaket = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        teksPenginapan = new javax.swing.JTextField();
        teksWisata = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pesan Paket");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnBatalPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan.setText("Batal Pesan");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnDaftarTransaksi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi.setText("Daftar Transaksi");
        btnDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksiActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatal.setText("Batalkan Pesanan");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Paket");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Penginapan");

        comboPaket.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        comboPaket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Tempat Wisata");

        teksPenginapan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        teksWisata.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Batal Pesan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDaftarTransaksi)
                            .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatalPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teksPenginapan)
                            .addComponent(teksWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel10)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(630, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatalPesan)
                        .addGap(18, 18, 18)
                        .addComponent(btnPembayaran))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(teksPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(teksWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnDaftarTransaksi)
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(btnLogout)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                    .addComponent(btnBatal)
                    .addGap(34, 34, 34)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnDaftarTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox comboPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField teksPenginapan;
    private javax.swing.JTextField teksWisata;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBatal
     */
    public javax.swing.JButton getBtnBatal() {
        return btnBatal;
    }

    /**
     * @return the btnBatalPesan
     */
    public javax.swing.JButton getBtnBatalPesan() {
        return btnBatalPesan;
    }

    /**
     * @return the btnDaftarTransaksi
     */
    public javax.swing.JButton getBtnDaftarTransaksi() {
        return btnDaftarTransaksi;
    }

    /**
     * @return the btnLogout
     */
    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * @return the btnPembayaran
     */
    public javax.swing.JButton getBtnPembayaran() {
        return btnPembayaran;
    }

    /**
     * @return the btnPesan
     */
    public javax.swing.JButton getBtnPesan() {
        return btnPesan;
    }

    /**
     * @return the comboPaket
     */
    public javax.swing.JComboBox getComboPaket() {
        return comboPaket;
    }

    /**
     * @return the teksPenginapan
     */
    public javax.swing.JTextField getTeksPenginapan() {
        return teksPenginapan;
    }

    /**
     * @return the teksWisata
     */
    public javax.swing.JTextField getTeksWisata() {
        return teksWisata;
    }
    
    public void addListener(ActionListener a) {
        btnBatal.addActionListener(a);
        btnBatalPesan.addActionListener(a);
        btnDaftarTransaksi.addActionListener(a);
        btnLogout.addActionListener(a);
        btnPembayaran.addActionListener(a);
        btnPesan.addActionListener(a);
        comboPaket.addActionListener(a);
    }
    
}
