package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRAKTIKUM
 */
public class KelolaPaketWisata extends javax.swing.JFrame {

    /**
     * Creates new form KelolaPaketWisata
     */
    public KelolaPaketWisata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesan = new javax.swing.JButton();
        btnBatalPesan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnDaftarTransaksi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnKelolaAkun = new javax.swing.JButton();
        btnKelolaWisata = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        teksNamaLokasi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnTambahLokasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboNamaLokasi = new javax.swing.JComboBox<String>();
        btnHapusLokasi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teksNamaPenginapan = new javax.swing.JTextField();
        teksFasilitasPenginapan = new javax.swing.JTextField();
        teksHargaPenginapan = new javax.swing.JTextField();
        teksKapasitasPenginapan = new javax.swing.JTextField();
        btnTambahPenginapan = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        comboLokasi = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        teksNamaWisata = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        teksFasilitasWisata = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        teksHargaWisata = new javax.swing.JTextField();
        btnTambahWisata = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboPenginapan = new javax.swing.JComboBox<String>();
        btnHapusPenginapan = new javax.swing.JButton();
        btnHapusWisata = new javax.swing.JButton();
        comboWisata = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();

        btnPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnBatalPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan.setText("Batal Pesan");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnDaftarTransaksi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi.setText("Daftar Transaksi");
        btnDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Kelola Paket Wisata");

        btnKelolaAkun.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnKelolaAkun.setText("Kelola Akun");
        btnKelolaAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaAkunActionPerformed(evt);
            }
        });

        btnKelolaWisata.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnKelolaWisata.setText("Kelola Wisata");
        btnKelolaWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaWisataActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Lokasi");

        btnTambahLokasi.setText("Tambah Lokasi");

        jLabel2.setText("Nama Lokasi");

        comboNamaLokasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        comboNamaLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNamaLokasiActionPerformed(evt);
            }
        });

        btnHapusLokasi.setText("Hapus Lokasi");

        jLabel3.setText("Nama ");

        jLabel4.setText("Fasilitas");

        jLabel5.setText("Harga");

        jLabel6.setText("Kapasitas");

        teksFasilitasPenginapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksFasilitasPenginapanActionPerformed(evt);
            }
        });

        btnTambahPenginapan.setText("Tambah Penginapan");

        jLabel9.setText("Status");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Unavailable" }));

        jLabel13.setText("Lokasi");

        comboLokasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel12.setText("Nama ");

        jLabel14.setText("Fasilitas");

        teksFasilitasWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksFasilitasWisataActionPerformed(evt);
            }
        });

        jLabel15.setText("Harga");

        btnTambahWisata.setText("Tambah Wisata");

        jLabel7.setText("Penginapan");

        comboPenginapan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnHapusPenginapan.setText("Hapus Penginapan");

        btnHapusWisata.setText("Hapus Wisata");

        comboWisata.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel8.setText("Wisata");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKelolaAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKelolaWisata, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jSeparator2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogout)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel1)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(teksNamaLokasi))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(123, 123, 123)
                                                            .addComponent(btnTambahLokasi)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(comboNamaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnHapusLokasi))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(comboLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(teksNamaPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel7))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(teksKapasitasPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(teksHargaPenginapan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnTambahPenginapan, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(comboPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(teksFasilitasPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(78, 78, 78)
                                                        .addComponent(teksNamaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel12)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnTambahWisata)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel14)
                                                                .addComponent(jLabel15)
                                                                .addComponent(jLabel8))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(comboWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(teksHargaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(teksFasilitasWisata, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(btnHapusWisata))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(btnHapusPenginapan)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(0, 16, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(243, 243, 243)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btnLogout))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teksNamaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboNamaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahLokasi)
                    .addComponent(btnHapusLokasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKelolaAkun)
                        .addGap(18, 18, 18)
                        .addComponent(btnKelolaWisata))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(teksHargaPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teksNamaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(teksNamaPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teksFasilitasWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(teksFasilitasPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teksHargaWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(teksKapasitasPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(comboWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnTambahWisata))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPenginapan)
                    .addComponent(btnHapusWisata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusPenginapan))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksiActionPerformed

    private void btnKelolaAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaAkunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaAkunActionPerformed

    private void btnKelolaWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaWisataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelolaWisataActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void comboNamaLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNamaLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNamaLokasiActionPerformed

    private void teksFasilitasWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksFasilitasWisataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksFasilitasWisataActionPerformed

    private void teksFasilitasPenginapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksFasilitasPenginapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksFasilitasPenginapanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnDaftarTransaksi;
    private javax.swing.JButton btnHapusLokasi;
    private javax.swing.JButton btnHapusPenginapan;
    private javax.swing.JButton btnHapusWisata;
    private javax.swing.JButton btnKelolaAkun;
    private javax.swing.JButton btnKelolaWisata;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnTambahLokasi;
    private javax.swing.JButton btnTambahPenginapan;
    private javax.swing.JButton btnTambahWisata;
    private javax.swing.JComboBox<String> comboLokasi;
    private javax.swing.JComboBox<String> comboNamaLokasi;
    private javax.swing.JComboBox<String> comboPenginapan;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboWisata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField teksFasilitasPenginapan;
    private javax.swing.JTextField teksFasilitasWisata;
    private javax.swing.JTextField teksHargaPenginapan;
    private javax.swing.JTextField teksHargaWisata;
    private javax.swing.JTextField teksKapasitasPenginapan;
    private javax.swing.JTextField teksNamaLokasi;
    private javax.swing.JTextField teksNamaPenginapan;
    private javax.swing.JTextField teksNamaWisata;
    // End of variables declaration//GEN-END:variables

    

    public void addListener(ActionListener a){
        btnHapusLokasi.addActionListener(a);
        btnHapusPenginapan.addActionListener(a);
        btnHapusWisata.addActionListener(a);
        btnKelolaAkun.addActionListener(a);
        btnKelolaWisata.addActionListener(a);
        btnLogout.addActionListener(a);
        btnTambahLokasi.addActionListener(a);
        btnTambahPenginapan.addActionListener(a);
        btnTambahWisata.addActionListener(a);
    }

    public JButton getBtnHapusLokasi() {
        return btnHapusLokasi;
    }

    public JButton getBtnKelolaAkun() {
        return btnKelolaAkun;
    }

    public JButton getBtnKelolaWisata() {
        return btnKelolaWisata;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnPembayaran() {
        return btnPembayaran;
    }

    public JButton getBtnTambah() {
        return getBtnTambahPenginapan();
    }

    public JButton getBtnTambahLokasi() {
        return btnTambahLokasi;
    }

    /**
     * @return the btnBatalPesan
     */
    public javax.swing.JButton getBtnBatalPesan() {
        return btnBatalPesan;
    }

    /**
     * @return the btnDaftarTransaksi
     */
    public javax.swing.JButton getBtnDaftarTransaksi() {
        return btnDaftarTransaksi;
    }

    /**
     * @return the btnHapusPenginapan
     */
    public javax.swing.JButton getBtnHapusPenginapan() {
        return btnHapusPenginapan;
    }

    /**
     * @return the btnHapusWisata
     */
    public javax.swing.JButton getBtnHapusWisata() {
        return btnHapusWisata;
    }

    /**
     * @return the btnPesan
     */
    public javax.swing.JButton getBtnPesan() {
        return btnPesan;
    }

    /**
     * @return the btnTambahPenginapan
     */
    public javax.swing.JButton getBtnTambahPenginapan() {
        return btnTambahPenginapan;
    }

    /**
     * @return the btnTambahWisata
     */
    public javax.swing.JButton getBtnTambahWisata() {
        return btnTambahWisata;
    }

    /**
     * @return the teksFasilitasPenginapan
     */
    public javax.swing.JTextField getTeksFasilitasPenginapan() {
        return teksFasilitasPenginapan;
    }

    /**
     * @return the teksFasilitasWisata
     */
    public javax.swing.JTextField getTeksFasilitasWisata() {
        return teksFasilitasWisata;
    }

    /**
     * @return the teksHargaPenginapan
     */
    public javax.swing.JTextField getTeksHargaPenginapan() {
        return teksHargaPenginapan;
    }

    /**
     * @return the teksHargaWisata
     */
    public javax.swing.JTextField getTeksHargaWisata() {
        return teksHargaWisata;
    }

    /**
     * @return the teksKapasitasPenginapan
     */
    public javax.swing.JTextField getTeksKapasitasPenginapan() {
        return teksKapasitasPenginapan;
    }

    /**
     * @return the teksNamaPenginapan
     */
    public javax.swing.JTextField getTeksNamaPenginapan() {
        return teksNamaPenginapan;
    }

    /**
     * @return the teksNamaWisata
     */
    public javax.swing.JTextField getTeksNamaWisata() {
        return teksNamaWisata;
    }

    /**
     * @return the comboLokasi
     */
    public javax.swing.JComboBox<String> getComboLokasi() {
        return comboLokasi;
    }

    /**
     * @return the comboNamaLokasi
     */
    public javax.swing.JComboBox<String> getComboNamaLokasi() {
        return comboNamaLokasi;
    }

    /**
     * @return the comboPenginapan
     */
    public javax.swing.JComboBox<String> getComboPenginapan() {
        return comboPenginapan;
    }

    /**
     * @return the comboStatus
     */
    public javax.swing.JComboBox<String> getComboStatus() {
        return comboStatus;
    }

    /**
     * @return the comboWisata
     */
    public javax.swing.JComboBox<String> getComboWisata() {
        return comboWisata;
    }

    /**
     * @return the teksNamaLokasi
     */
    public javax.swing.JTextField getTeksNamaLokasi() {
        return teksNamaLokasi;
    }
    
    

}
