package View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRAKTIKUM
 */
public class PesanPaket extends javax.swing.JFrame {

    /**
     * Creates new form PesanPaket
     */
    public PesanPaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBatalPesan = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnDaftarTransaksi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        teksTanggal = new javax.swing.JTextField();
        comboLokasi = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        teksJumlahOrang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textJumlahHari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBatalPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan.setText("Batal Pesan");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        btnPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnDaftarTransaksi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi.setText("Daftar Transaksi");
        btnDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksiActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pesan Paket");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Tanggal Keberangkatan");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Lokasi Tujuan");

        teksTanggal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        teksTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksTanggalActionPerformed(evt);
            }
        });

        comboLokasi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        comboLokasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        comboLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLokasiActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Jumlah Orang");

        teksJumlahOrang.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        teksJumlahOrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksJumlahOrangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah Hari");

        textJumlahHari.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        textJumlahHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(226, 226, 226)
                        .addComponent(btnLogout)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(teksJumlahOrang)
                                    .addComponent(textJumlahHari)
                                    .addComponent(teksTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(comboLokasi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDaftarTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(591, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesan)
                    .addComponent(jLabel1)
                    .addComponent(teksTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textJumlahHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(teksJumlahOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(btnBatalPesan)
                    .addGap(18, 18, 18)
                    .addComponent(btnPembayaran)
                    .addGap(18, 18, 18)
                    .addComponent(btnDaftarTransaksi)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void teksTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksTanggalActionPerformed

    private void comboLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLokasiActionPerformed

    private void teksJumlahOrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksJumlahOrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksJumlahOrangActionPerformed

    private void textJumlahHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJumlahHariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnDaftarTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField teksJumlahOrang;
    private javax.swing.JTextField teksTanggal;
    private javax.swing.JTextField textJumlahHari;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the comboLokasi
     */
    public javax.swing.JComboBox getComboLokasi() {
        return comboLokasi;
    }
    
    public void addListener(ActionListener a) {
        comboLokasi.addActionListener(a);
        btnSubmit.addActionListener(a);
        btnPesan.addActionListener(a);
        btnPembayaran.addActionListener(a);
        btnBatalPesan.addActionListener(a);
        btnDaftarTransaksi.addActionListener(a);
        btnLogout.addActionListener(a);
    }

    /**
     * @return the btnSubmit
     */
    public javax.swing.JButton getBtnSubmit() {
        return btnSubmit;
    }

    /**
     * @return the teksJumlahOrang
     */
    public javax.swing.JTextField getTeksJumlahOrang() {
        return teksJumlahOrang;
    }

    /**
     * @return the textJumlahHari
     */
    public javax.swing.JTextField getTextJumlahHari() {
        return textJumlahHari;
    }

    /**
     * @return the btnBatalPesan
     */
    public javax.swing.JButton getBtnBatalPesan() {
        return btnBatalPesan;
    }

    /**
     * @return the btnDaftarTransaksi
     */
    public javax.swing.JButton getBtnDaftarTransaksi() {
        return btnDaftarTransaksi;
    }

    /**
     * @return the btnLogout
     */
    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * @return the btnPembayaran
     */
    public javax.swing.JButton getBtnPembayaran() {
        return btnPembayaran;
    }

    /**
     * @return the btnPesan
     */
    public javax.swing.JButton getBtnPesan() {
        return btnPesan;
    }

    /**
     * @return the teksTanggal
     */
    public javax.swing.JTextField getTeksTanggal() {
        return teksTanggal;
    }

}
