package View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRAKTIKUM
 */
public class PesanPaket4 extends javax.swing.JFrame {

    /**
     * Creates new form PesanPaket4
     */
    public PesanPaket4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPembayaran = new javax.swing.JButton();
        btnDaftarTransaksi = new javax.swing.JButton();
        btnBatalPesan = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnPembayaran1 = new javax.swing.JButton();
        btnDaftarTransaksi1 = new javax.swing.JButton();
        btnBatalPesan1 = new javax.swing.JButton();
        btnPesan1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnSubmit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teksLokasi = new javax.swing.JTextField();
        teksWisata = new javax.swing.JTextField();
        teksPenginapan = new javax.swing.JTextField();
        teksJml = new javax.swing.JTextField();
        teksTglBerangkat = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        btnPembayaran.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnDaftarTransaksi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi.setText("Daftar Transaksi");
        btnDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksiActionPerformed(evt);
            }
        });

        btnBatalPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan.setText("Batal Pesan");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        btnPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pesan Paket");

        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPembayaran1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran1.setText("Pembayaran");
        btnPembayaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaran1ActionPerformed(evt);
            }
        });

        btnDaftarTransaksi1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi1.setText("Daftar Transaksi");
        btnDaftarTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksi1ActionPerformed(evt);
            }
        });

        btnBatalPesan1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan1.setText("Batal Pesan");
        btnBatalPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesan1ActionPerformed(evt);
            }
        });

        btnPesan1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan1.setText("Pesan Tiket");
        btnPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesan1ActionPerformed(evt);
            }
        });

        btnLogout1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout1.setText("Logout");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pesan Paket");

        btnSubmit1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSubmit1.setText("Submit");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Lokasi");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Tempat Wisata");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Penginapan");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Tanggal Berangkat");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Jumlah hari / orang");

        teksLokasi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        teksLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksLokasiActionPerformed(evt);
            }
        });

        teksWisata.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        teksPenginapan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        teksJml.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        teksTglBerangkat.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        teksTglBerangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksTglBerangkatActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDaftarTransaksi1)
                    .addComponent(btnPembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatalPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teksJml, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(teksTglBerangkat)
                            .addComponent(teksPenginapan)
                            .addComponent(teksWisata)
                            .addComponent(teksLokasi))))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogout1))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnLogout1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(teksPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(teksLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(teksWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(teksTglBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(teksJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit1)
                    .addComponent(btnKembali))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnPesan1)
                .addGap(18, 18, 18)
                .addComponent(btnBatalPesan1)
                .addGap(18, 18, 18)
                .addComponent(btnPembayaran1)
                .addGap(18, 18, 18)
                .addComponent(btnDaftarTransaksi1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksiActionPerformed

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPembayaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaran1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaran1ActionPerformed

    private void btnDaftarTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksi1ActionPerformed

    private void btnBatalPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesan1ActionPerformed

    private void btnPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesan1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void teksLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksLokasiActionPerformed

    private void teksTglBerangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teksTglBerangkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teksTglBerangkatActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnBatalPesan1;
    private javax.swing.JButton btnDaftarTransaksi;
    private javax.swing.JButton btnDaftarTransaksi1;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPembayaran1;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnPesan1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField teksJml;
    private javax.swing.JTextField teksLokasi;
    private javax.swing.JTextField teksPenginapan;
    private javax.swing.JTextField teksTglBerangkat;
    private javax.swing.JTextField teksWisata;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBatalPesan1
     */
    public javax.swing.JButton getBtnBatalPesan1() {
        return btnBatalPesan1;
    }

    /**
     * @return the btnDaftarTransaksi1
     */
    public javax.swing.JButton getBtnDaftarTransaksi1() {
        return btnDaftarTransaksi1;
    }

    /**
     * @return the btnLogout1
     */
    public javax.swing.JButton getBtnLogout1() {
        return btnLogout1;
    }

    /**
     * @return the btnPembayaran1
     */
    public javax.swing.JButton getBtnPembayaran1() {
        return btnPembayaran1;
    }

    /**
     * @return the btnPesan1
     */
    public javax.swing.JButton getBtnPesan1() {
        return btnPesan1;
    }

    /**
     * @return the btnSubmit1
     */
    public javax.swing.JButton getBtnSubmit1() {
        return btnSubmit1;
    }

    /**
     * @return the teksJml
     */
    public javax.swing.JTextField getTeksJml() {
        return teksJml;
    }

    /**
     * @return the teksLokasi
     */
    public javax.swing.JTextField getTeksLokasi() {
        return teksLokasi;
    }

    /**
     * @return the teksPenginapan
     */
    public javax.swing.JTextField getTeksPenginapan() {
        return teksPenginapan;
    }

    /**
     * @return the teksTglBerangkat
     */
    public javax.swing.JTextField getTeksTglBerangkat() {
        return teksTglBerangkat;
    }

    /**
     * @return the teksWisata
     */
    public javax.swing.JTextField getTeksWisata() {
        return teksWisata;
    }
    
    public void addListener (ActionListener a) {
        btnBatalPesan1.addActionListener(a);
        btnDaftarTransaksi1.addActionListener(a);
        btnKembali.addActionListener(a);
        btnLogout.addActionListener(a);
        btnPembayaran1.addActionListener(a);
        btnPesan1.addActionListener(a);
        btnSubmit1.addActionListener(a);
    }

    /**
     * @return the btnKembali
     */
    public javax.swing.JButton getBtnKembali() {
        return btnKembali;
    }
    
}
