package View;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRAKTIKUM
 */
public class PesanPaket3 extends javax.swing.JFrame {

    /**
     * Creates new form PesanPaket3
     */
    public PesanPaket3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesan = new javax.swing.JButton();
        btnBatalPesan = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnDaftarTransaksi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPesan1 = new javax.swing.JButton();
        btnBatalPesan1 = new javax.swing.JButton();
        btnPembayaran1 = new javax.swing.JButton();
        btnDaftarTransaksi1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboPenginapan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teksDetailPenginapan = new javax.swing.JTextArea();
        btnKembali = new javax.swing.JButton();
        btnLanjut = new javax.swing.JButton();

        btnPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan.setText("Pesan Tiket");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnBatalPesan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan.setText("Batal Pesan");
        btnBatalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesanActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnDaftarTransaksi.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi.setText("Daftar Transaksi");
        btnDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pesan Paket");

        btnPesan1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPesan1.setText("Pesan Tiket");
        btnPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesan1ActionPerformed(evt);
            }
        });

        btnBatalPesan1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBatalPesan1.setText("Batal Pesan");
        btnBatalPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPesan1ActionPerformed(evt);
            }
        });

        btnPembayaran1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnPembayaran1.setText("Pembayaran");
        btnPembayaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaran1ActionPerformed(evt);
            }
        });

        btnDaftarTransaksi1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnDaftarTransaksi1.setText("Daftar Transaksi");
        btnDaftarTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarTransaksi1ActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Pilih Lokasi Penginapan");

        comboPenginapan.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        comboPenginapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPenginapanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Detail Lokasi Penginapan");

        teksDetailPenginapan.setColumns(20);
        teksDetailPenginapan.setRows(5);
        jScrollPane1.setViewportView(teksDetailPenginapan);

        btnKembali.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnLanjut.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnLanjut.setText("Lanjutkan");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDaftarTransaksi1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBatalPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPenginapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesan1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatalPesan1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPembayaran1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnDaftarTransaksi1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnLanjut))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnBatalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesanActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksiActionPerformed

    private void btnPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesan1ActionPerformed

    private void btnBatalPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPesan1ActionPerformed

    private void btnPembayaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaran1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaran1ActionPerformed

    private void btnDaftarTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarTransaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarTransaksi1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void comboPenginapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPenginapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPenginapanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPesan;
    private javax.swing.JButton btnBatalPesan1;
    private javax.swing.JButton btnDaftarTransaksi;
    private javax.swing.JButton btnDaftarTransaksi1;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPembayaran1;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnPesan1;
    private javax.swing.JComboBox comboPenginapan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea teksDetailPenginapan;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBatalPesan1
     */
    public javax.swing.JButton getBtnBatalPesan1() {
        return btnBatalPesan1;
    }

    /**
     * @return the btnDaftarTransaksi1
     */
    public javax.swing.JButton getBtnDaftarTransaksi1() {
        return btnDaftarTransaksi1;
    }

    /**
     * @return the btnKembali
     */
    public javax.swing.JButton getBtnKembali() {
        return btnKembali;
    }

    /**
     * @return the btnLanjut
     */
    public javax.swing.JButton getBtnLanjut() {
        return btnLanjut;
    }

    /**
     * @return the btnLogout
     */
    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    /**
     * @return the btnPembayaran1
     */
    public javax.swing.JButton getBtnPembayaran1() {
        return btnPembayaran1;
    }

    /**
     * @return the btnPesan1
     */
    public javax.swing.JButton getBtnPesan1() {
        return btnPesan1;
    }

    /**
     * @return the comboPenginapan
     */
    public javax.swing.JComboBox getComboPenginapan() {
        return comboPenginapan;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the teksDetailPenginapan
     */
    public javax.swing.JTextArea getTeksDetailPenginapan() {
        return teksDetailPenginapan;
    }
    
    public void addListener(ActionListener a) {
        btnBatalPesan1.addActionListener(a);
        btnDaftarTransaksi1.addActionListener(a);
        btnKembali.addActionListener(a);
        btnLanjut.addActionListener(a);
        btnLogout.addActionListener(a);
        btnPembayaran1.addActionListener(a);
        btnPesan1.addActionListener(a);
        comboPenginapan.addActionListener(a);
    }
    
}
